### ISSUE TITLE
Did you run IOS

### ISSUE THREAD

**Issue by ompangchu** [zolomohan/react-native-firebase-ml-text-recognition#1]
Thanks for sharing awesome library.

I wanna use both IOS and Android devices.

Did you run IOS?

If difficult, do you have plan?

**Comment by zolomohan** [comment]
Hi @ompangchu. This is not a library. This is just an application that implements Firebase's ML Text recognition module.
Please refer to this article if you'd like to learn how to build this. https://zolomohan.hashnode.dev/react-native-firebase-text-recognition
